name: app-service

services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./backend:/home/web/code

  frontend:
    build:
      context: ./app/frontend/
      dockerfile: Dockerfile
      target: dev
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
      - NEXT_TELEMETRY_DISABLED=1
    ports:
      - "3000:3000"
    volumes:
      - ./app/frontend:/app
      - /app/node_modules
      - /app/.next

  proxy:
    command:
      - "--api.insecure=True"