name: app-service

services:
  app-backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env
    volumes:
      - ./:/home/web/code

  app-frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
      target: dev
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - ./frontend:/app
      - /node_modules
      - /.next
